<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Switch Template</title>
    <link href="//cdn.tms-dist.lan:433:433/styles/fonts/Heebo_Googlefont.css" rel="stylesheet">
    <link href="//cdn.tms-dist.lan:433:433/styles/css/bootstrap.min.css" rel="stylesheet"></link>
    <link rel="stylesheet" href="dist/css/style.css">
    <script src="//cdn.tms-dist.lan:433:433/styles/js/scrollreveal.min.js"></script>
</head>
<body class="is-boxed has-animations">
    <div class="body-wrap boxed-container">
        <header class="site-header">
            <div class="container">
                <div class="site-header-inner">
                    <div class="brand header-brand">
                        <h1 class="m-0">
                            <a href="#">
								<img class="header-logo-image asset-light" src="dist/images/logo-light.svg" alt="Logo">
								<img class="header-logo-image asset-dark" src="dist/images/logo-dark.svg" alt="Logo">
                            </a>
                        </h1>
                    </div>
                </div>
                <script src="//cdn.tms-dist.lan:433:433/styles/js/bootstrap.js"></script>
                <script src="//cdn.tms-dist.lan:433:433/styles/js/jquery-3.4.1.min.js"></script>
<script src="//cdn.tms-dist.lan:433:433/styles/font-awesome/js/all.min.js"></script>

<head>
//	<?php include_once("../actions/gtag.php"); ?>
</head>
<div class="container">
	<nav class="navbar navbar-inverse navbar-sticky navbar-expand-md navbar-light bg-light">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Tenant Management System</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav" style="float:left;">
					<?php session_start();
					if (isset($_SESSION['manager_logged_in']) && $_SESSION['manager_logged_in'] == true) { ?>
						<li class="nav-item">
							<link rel="stylesheet" href="//cdn.tms-dist.lan:433/styles/css/man-custom.css" type="text/css" />
							<a class="nav-link" id="verifier" href="#verifyusers">
								Verify Users
							</a>
						</li>
						<li class="nav-item">
							<a onclick="ten()" href="#tenants" class="nav-link">Tenants</a>
						</li>
						<li class="nav-item">
							<a href="#processpayments" class="nav-link" onclick="process()">Process Rent Payments</a>
						</li>
						<li class="nav-item">
							<a href="#tenants" class="nav-link" id="ten_det">Tenants Details</a>
						</li>
						<li class="nav-item">
							<a href="#addtenant" onclick="addTen()" class="nav-link" id="add_ten">New Tenant</a>
						</li>
						<li class="dropdown" role="presentation" style="padding: 0px 25px">
							<a href="#more" class="dropdown-toggle" data-menu="more-navs" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="more_nav"><i class="fa fa-arrow-circle-down"></i><span class="caret"></span></a>
							<ul class="dropdown-menu dropdown-content">
								<li class="nav-item"><a href="#remtenant" onclick="remTen()" class="nav-link" id="rem_ten">Remove Tenant</a></li>
						<span class="divider" style="background-color: black;height: 1px;width: 100%;display: block;"></span>
								<li class="nav-item"><a href="#housedet" onclick="houseDet()" class="nav-link" id="rem_ten">House Details</a></li>
							</ul>
						</li>
						<li class="nav-item">
							<a href="#remtenant" onclick="remTen()" class="nav-link more-navs" id="rem_ten">Remove Tenant</a>
						</li>
						<li class="nav-item"><a href="#housedet" onclick="houseDet()" class="nav-link more-navs" id="rem_ten">House Details</a></li>
					<?php
					} else if (isset($_SESSION['client_logged_in']) && $_SESSION['client_logged_in'] == true) {
					?>
						<li class="nav-item">
							<a href="javascript:void(0)">No content to navigate to.</a>
						</li>
					<?php
					} ?>
				</ul>
				<ul class="nav navbar-nav navbar-right" style="float:right;">
					<?php if (isset($_SESSION['logged_in']) && $_SESSION['logged_in'] == false) { ?>
						<li>
							<button style="margin-top: 15px;background:transparent;border:none;color:darkgrey" onclick="document.getElementById('id02').style.display='block'; document.getElementById('id01').style.display='none'"><span class="glyphicon glyphicon-user"></span> Sign Up</button>
						</li>
						<li>
							<button style="margin-top: 15px;background:transparent;border:none;color:darkgrey" onclick="document.getElementById('id01').style.display='block'; document.getElementById('id02').style.display='none'"><span class="glyphicon glyphicon-log-in"></span> Login</button>
						</li>
					<?php } else if (isset($_SESSION['logged_in']) && $_SESSION['logged_in'] == true) { ?>
						<li>
							<a class="navbar-item" href="/actions/logout.php"><span class="glyphicon glyphicon-log-out"></span> Logout <?php echo $_SESSION['fName']; ?></a>
						</li>
					<?php } else { ?>
						<li>
							<button style="margin-top: 15px;background:transparent;border:none;color:darkgrey" onclick="document.getElementById('id02').style.display='block'; document.getElementById('id01').style.display='none'"><span class="glyphicon glyphicon-user"></span> Sign Up</button>
						</li>
						<li>
							<button style="margin-top: 15px;background:transparent;border:none;color:darkgrey" onclick="document.getElementById('id01').style.display='block'; document.getElementById('id02').style.display='none'"><span class="glyphicon glyphicon-log-in"></span> Login</button>
						</li>
					<?php } ?>
				</ul>
			</div>
		</div>
	</nav>
</div>
<script>
	var verifier = document.getElementById("verifier");
	if (verifier != null) {
		verifier.addEventListener("click", function() {
			$("#LTContent").css({
				display: "none"
			});
			$("#ten_list").css({
				display: "none"
			});
			$('#processrent').css({
				display: 'none'
			});
			$('#tendet').css({
				display: 'none'
			});
			$('#newten').css({
				display: 'none'
			})
			$('#Tenact').hide()
			$("#verify").load("/includes/ver.php");
		});
	}
	$('li.nav-item').on('click', () => {
		$('.navbar-collapse').removeClass('collapse')
		$('.navbar-collapse').addClass('collapsing')
		$('.navbar-collapse').animate({
			height: '0px',
		})
		$('.navbar-collapse').removeClass('collapsing')
		$('.navbar-collapse').removeClass('show')
		$('.navbar-collapse').addClass('collapse')
	})
	if (window.location.pathname == '/man/' || location.pathname == '/man')
		tendet()
</script>
<style>
	[data-menu="more-navs"]:hover,
	[data-toggle="more-navs"]:focus {
		background-color: #2980B9;
	}

	.dropdown-content {
		display: none !important;
		position: absolute;
		background-color: #f1f1f1;
		min-width: 160px;
		box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
		z-index: 1;
	}

	@media (max-width: 752px) {
		.more-navs {
			display: block !important;
		}

		#more_nav {
			display: none !important;
		}
	}

	@media (min-width: 753px) {
		#more_nav {
			display: block !important;
		}

		.more-navs {
			display: none !important;
		}
	}
</style>
            </div>
        </header>

        <main>
            <section class="hero">
                <div class="container">
                    <div class="hero-inner">
						<div class="hero-copy">
	                        <h1 class="hero-title mt-0">Landing template for startups</h1>
	                        <p class="hero-paragraph">Our landing page template works on all devices, so you only have to set it up once, and get beautiful results forever.</p>
	                        <div class="hero-cta">
								<a class="button button-primary" href="#">Buy it now</a>
								<div class="lights-toggle">
									<input id="lights-toggle" type="checkbox" name="lights-toggle" class="switch" checked="checked">
									<label for="lights-toggle" class="text-xs"><span>Turn me <span class="label-text">dark</span></span></label>
								</div>
							</div>
						</div>
						<div class="hero-media">
							<div class="header-illustration">
								<img class="header-illustration-image asset-light" src="dist/images/header-illustration-light.svg" alt="Header illustration">
								<img class="header-illustration-image asset-dark" src="dist/images/header-illustration-dark.svg" alt="Header illustration">
							</div>
							<div class="hero-media-illustration">
								<img class="hero-media-illustration-image asset-light" src="dist/images/hero-media-illustration-light.svg" alt="Hero media illustration">
								<img class="hero-media-illustration-image asset-dark" src="dist/images/hero-media-illustration-dark.svg" alt="Hero media illustration">
							</div>
							<div class="hero-media-container">
								<img class="hero-media-image asset-light" src="dist/images/hero-media-light.svg" alt="Hero media">
								<img class="hero-media-image asset-dark" src="dist/images/hero-media-dark.svg" alt="Hero media">
							</div>
						</div>
                    </div>
                </div>
            </section>

            <section class="features section">
                <div class="container">
					<div class="features-inner section-inner has-bottom-divider">
						<div class="features-header text-center">
							<div class="container-sm">
								<h2 class="section-title mt-0">The Product</h2>
	                            <p class="section-paragraph">Lorem ipsum is common placeholder text used to demonstrate the graphic elements of a document or visual presentation.</p>
								<div class="features-image">
									<img class="features-illustration asset-dark" src="dist/images/features-illustration-dark.svg" alt="Feature illustration">
									<img class="features-box asset-dark" src="dist/images/features-box-dark.svg" alt="Feature box">
									<img class="features-illustration asset-dark" src="dist/images/features-illustration-top-dark.svg" alt="Feature illustration top">
									<img class="features-illustration asset-light" src="dist/images/features-illustration-light.svg" alt="Feature illustration">
									<img class="features-box asset-light" src="dist/images/features-box-light.svg" alt="Feature box">
									<img class="features-illustration asset-light" src="dist/images/features-illustration-top-light.svg" alt="Feature illustration top">
								</div>
							</div>
                        </div>
                        <div class="features-wrap">
                            <div class="feature is-revealing">
                                <div class="feature-inner">
                                    <div class="feature-icon">
										<img class="asset-light" src="dist/images/feature-01-light.svg" alt="Feature 01">
										<img class="asset-dark" src="dist/images/feature-01-dark.svg" alt="Feature 01">
                                    </div>
									<div class="feature-content">
                                    	<h3 class="feature-title mt-0">Discover</h3>
                                    	<p class="text-sm mb-0">Lorem ipsum dolor sit amet, consecte adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua dui.</p>
									</div>
								</div>
                            </div>
							<div class="feature is-revealing">
                                <div class="feature-inner">
                                    <div class="feature-icon">
										<img class="asset-light" src="dist/images/feature-02-light.svg" alt="Feature 02">
										<img class="asset-dark" src="dist/images/feature-02-dark.svg" alt="Feature 02">
                                    </div>
									<div class="feature-content">
                                    	<h3 class="feature-title mt-0">Discover</h3>
                                    	<p class="text-sm mb-0">Lorem ipsum dolor sit amet, consecte adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua dui.</p>
									</div>
								</div>
                            </div>
							<div class="feature is-revealing">
                                <div class="feature-inner">
                                    <div class="feature-icon">
										<img class="asset-light" src="dist/images/feature-03-light.svg" alt="Feature 03">
										<img class="asset-dark" src="dist/images/feature-03-dark.svg" alt="Feature 03">
                                    </div>
									<div class="feature-content">
                                    	<h3 class="feature-title mt-0">Discover</h3>
                                    	<p class="text-sm mb-0">Lorem ipsum dolor sit amet, consecte adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua dui.</p>
									</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

			<section class="cta section">
                <div class="container-sm">
                    <div class="cta-inner section-inner">
                        <div class="cta-header text-center">
                            <h2 class="section-title mt-0">Get it and Switch</h2>
                            <p class="section-paragraph">Lorem ipsum is common placeholder text used to demonstrate the graphic elements of a document or visual presentation.</p>
							<div class="cta-cta">
								<a class="button button-primary" href="#">Buy it now</a>
							</div>
					    </div>
                    </div>
                </div>
            </section>
        </main>

        <footer class="site-footer has-top-divider">
            <div class="container">
                <div class="site-footer-inner">
                    <div class="brand footer-brand">
                        <a href="#">
							<img class="asset-light" src="dist/images/logo-light.svg" alt="Logo">
							<img class="asset-dark" src="dist/images/logo-dark.svg" alt="Logo">
                        </a>
                    </div>
                    <ul class="footer-links list-reset">
                        <li>
                            <a href="#">Contact</a>
                        </li>
                        <li>
                            <a href="#">About us</a>
                        </li>
                        <li>
                            <a href="#">FAQ's</a>
                        </li>
                        <li>
                            <a href="#">Support</a>
                        </li>
                    </ul>
                    <ul class="footer-social-links list-reset">
                        <li>
                            <a href="#">
                                <span class="screen-reader-text">Facebook</span>
                                <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M6.023 16L6 9H3V6h3V4c0-2.7 1.672-4 4.08-4 1.153 0 2.144.086 2.433.124v2.821h-1.67c-1.31 0-1.563.623-1.563 1.536V6H13l-1 3H9.28v7H6.023z" fill="#FFF"/>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="screen-reader-text">Twitter</span>
                                <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M16 3c-.6.3-1.2.4-1.9.5.7-.4 1.2-1 1.4-1.8-.6.4-1.3.6-2.1.8-.6-.6-1.5-1-2.4-1-1.7 0-3.2 1.5-3.2 3.3 0 .3 0 .5.1.7-2.7-.1-5.2-1.4-6.8-3.4-.3.5-.4 1-.4 1.7 0 1.1.6 2.1 1.5 2.7-.5 0-1-.2-1.5-.4C.7 7.7 1.8 9 3.3 9.3c-.3.1-.6.1-.9.1-.2 0-.4 0-.6-.1.4 1.3 1.6 2.3 3.1 2.3-1.1.9-2.5 1.4-4.1 1.4H0c1.5.9 3.2 1.5 5 1.5 6 0 9.3-5 9.3-9.3v-.4C15 4.3 15.6 3.7 16 3z" fill="#FFF"/>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="screen-reader-text">Google</span>
                                <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M7.9 7v2.4H12c-.2 1-1.2 3-4 3-2.4 0-4.3-2-4.3-4.4 0-2.4 2-4.4 4.3-4.4 1.4 0 2.3.6 2.8 1.1l1.9-1.8C11.5 1.7 9.9 1 8 1 4.1 1 1 4.1 1 8s3.1 7 7 7c4 0 6.7-2.8 6.7-6.8 0-.5 0-.8-.1-1.2H7.9z" fill="#FFF"/>
                                </svg>
                            </a>
                        </li>
                    </ul>
                    <div class="footer-copyright">&copy; 2018 Switch, all rights reserved</div>
                </div>
            </div>
        </footer>
    </div>

    <script src="dist/js/main.min.js"></script>
</body>
</html>
